In [ ]:
不管学习离散数据还是连续数据 我们一定要知道数据的存在

In [3]:
import numpy as np
import pandas as pd  

In [4]:
# 生成年龄的数据
# random是随机模块 normal是正常值 
# 25 代表生成的数据的在25左右
# 5 代表生成的数据的值和25的差是5左右
# 100代表生成100个这样的值
age = np.random.normal(25,5,100)
age


array([22.90016136, 23.30744634, 31.21680307, 22.24933453, 27.18579725,
       29.43782569, 18.90451521, 21.30777916, 17.64312858, 18.33983438,
       23.93578506, 26.73009015, 23.58657044, 22.79364651, 25.20306779,
       27.07793181, 17.69064028,  7.65881541, 21.80116233, 24.67043618,
       20.79694532, 23.36756284, 31.0722802 , 17.92603096, 23.05191558,
       32.39055904, 30.4727348 , 24.54509877, 31.66155244, 19.42128484,
       19.91624516, 24.26210114, 27.1468737 , 21.47418604, 23.56788539,
       31.02124773, 27.03470993, 38.47819455, 22.37905774, 21.13889441,
       24.58015731, 27.53114857, 26.6173664 , 21.72751025, 21.1768276 ,
       28.97851578, 22.12221714, 18.44417023, 29.40873313, 22.96670294,
       21.93802433, 17.41447589, 32.89482528, 12.26966727, 17.63693682,
       30.42592558, 23.62106299, 22.98080204, 22.73376407, 23.32370791,
       22.22488331, 29.20147662, 20.93463182, 24.95063555, 21.8669749 ,
       24.39258325, 29.40924254, 19.72548419, 31.26305041, 24.95

In [5]:
# 生成年龄的数据
# random是随机模块 normal是正常值 
# 25 代表生成的数据的在25左右
# 5 代表生成的数据的值和25的差是5左右
# 100代表生成100个这样的值
age = np.random.normal(25,5,100)
# 根据上一行打印数来的代码可知数据类型为浮点型 的小数 不方便观察
# 可以使用 .astype()将数据变为整数 括号内是想要转化的数据类型
age_new = np.random.normal(25,5,100).astype(int)
age_new

array([25, 21, 21, 22, 26, 25, 31, 27, 18, 20, 26, 24, 35, 26, 25, 30, 28,
       22, 26, 19, 19, 28, 29, 15, 23, 17, 24, 26, 34, 23, 31, 27, 27, 27,
       24, 24, 30, 21, 32, 26, 23, 31, 22, 23, 16, 24, 29, 25, 20, 22, 24,
       24, 19, 25, 26, 22, 26, 22, 21, 15, 28, 24, 25, 16, 28, 19, 26, 27,
       25, 17, 20, 18, 21, 26, 25, 16, 23, 25, 26, 26, 23, 25, 24, 16, 22,
       26, 18, 30, 16, 23, 22, 24, 13, 31, 25, 34, 15, 26, 25, 29])

In [6]:
# 生成成绩的数据
score = np.random.normal(20,8,100).astype(int)
score

array([ 5, 21, 27, 26, 12,  8, 21, 24, 14,  8,  9, 17, 14, 23, 20, 28, 16,
       24, 19, 13, 23, 21, 21,  7, 34, 24, 24, 32, 15, 37, 25, 13, 14, 19,
       33, 21, 17, 25, 16, 11, 23,  6, 13, 33, 19, 17, 37, 22, 23, 21, 24,
       30, 26, 14, 26, 28, 34, 16, 25, 12, 18, 15, 17,  3, 29, 28, 10, 21,
       13, 17, 14, 28, 13, 20, 21, 10, 37, 32, 30, 15, 17, 11, 20, 33, 11,
       28, 32, 19, 12, 20, 29, 25, 30, 15, 16, 19, 21, 30,  3, 26])

In [20]:
# 成绩和年龄数据生成完毕将他们转化为二维列表
data = pd.DataFrame({"age":age_new,"score":score})  # 将二维列表是字典数据所以要加上{}
print(data)

    age  score
0    25      5
1    21     21
2    21     27
3    22     26
4    26     12
..  ...    ...
95   34     19
96   15     21
97   26     30
98   25      3
99   29     26

[100 rows x 2 columns]


In [ ]:
# 使用.copy()方法可以粘贴数据去做数据处理

In [21]:
data_new=data.copy() # 赋值data_new的数据
data_new

age  score
0    25      5
1    21     21
2    21     27
3    22     26
4    26     12
..  ...    ...
95   34     19
96   15     21
97   26     30
98   25      3
99   29     26

[100 rows x 2 columns]

In [ ]:
# .cut() 可以自定义区间进行数据的分类

In [22]:
# 对数据年龄这一列数据按照一定区间值进行分类   （.cut() 可以自定义区间进行数据的分类）
#  data_new.age 代表data_new这一个二维数据中age这一列数据  
# bins=[]是进行自主指定区间值进行区间设置时使用的方法
#  [1,12,18,36,50] 代表 设置的区间分别为 1,12 12,18 18,36 36,50  左边为开区间 后边为闭区间
pd.cut(data_new.age,bins=[1,12,18,36,50])

0     (18, 36]
1     (18, 36]
2     (18, 36]
3     (18, 36]
4     (18, 36]
        ...   
95    (18, 36]
96    (12, 18]
97    (18, 36]
98    (18, 36]
99    (18, 36]
Name: age, Length: 100, dtype: category
Categories (4, interval[int64, right]): [(1, 12] < (12, 18] < (18, 36] < (36, 50]]

In [24]:
# 数据进行区间的分类之后可以把新生成的列区间，添加到列表中  
# data_new['区间'] 中中括号的区间 代表在data_new这个二维数据中添加了一列名为 区间 的列数据
data_new['区间']=pd.cut(data_new.age,bins=[1,12,18,36,50])
data_new

age  score        区间
0    25      5  (18, 36]
1    21     21  (18, 36]
2    21     27  (18, 36]
3    22     26  (18, 36]
4    26     12  (18, 36]
..  ...    ...       ...
95   34     19  (18, 36]
96   15     21  (12, 18]
97   26     30  (18, 36]
98   25      3  (18, 36]
99   29     26  (18, 36]

[100 rows x 3 columns]

In [28]:
# 调用.cat.categories可以查看设置的分类区间的具体数量
data_new.区间.cat.categories
# 由数据可知设置了四个区间

IntervalIndex([(1, 12], (12, 18], (18, 36], (36, 50]], dtype='interval[int64, right]')

In [29]:
# .value_counts()可以统计区间中数据的个数
data_new.区间.value_counts()

区间
(18, 36]    86
(12, 18]    14
(1, 12]      0
(36, 50]     0
Name: count, dtype: int64

In [31]:
data2 = data.copy()
print(data2)

    age  score
0    25      5
1    21     21
2    21     27
3    22     26
4    26     12
..  ...    ...
95   34     19
96   15     21
97   26     30
98   25      3
99   29     26

[100 rows x 2 columns]


In [ ]:
# pd.qcut 也可以进行数据的区间设置 但与cut()不同的是 
# .qcut不可以指定区间值(区间值由系统生成)，但可以指定有几个区间

In [33]:
# data2是要进行数据区间设置的值   4代表设置4个区间
pd.qcut(data2.age,4)

0       (24.0, 26.0]
1     (12.999, 21.0]
2     (12.999, 21.0]
3       (21.0, 24.0]
4       (24.0, 26.0]
           ...      
95      (26.0, 35.0]
96    (12.999, 21.0]
97      (24.0, 26.0]
98      (24.0, 26.0]
99      (26.0, 35.0]
Name: age, Length: 100, dtype: category
Categories (4, interval[float64, right]): [(12.999, 21.0] < (21.0, 24.0] < (24.0, 26.0] < (26.0, 35.0]]

In [34]:
# 使用labels可以给区间起名字
pd.qcut(data2.age,4,labels=['少年','青年','中年','老年'])

0     中年
1     少年
2     少年
3     青年
4     中年
      ..
95    老年
96    少年
97    中年
98    中年
99    老年
Name: age, Length: 100, dtype: category
Categories (4, object): ['少年' < '青年' < '中年' < '老年']

In [36]:
# 可以将生成的区间加入到二维数据中
data2['年龄']=pd.qcut(data2.age,4,labels=['少年','青年','中年','老年'])
data2

age  score  年龄
0    25      5  中年
1    21     21  少年
2    21     27  少年
3    22     26  青年
4    26     12  中年
..  ...    ...  ..
95   34     19  老年
96   15     21  少年
97   26     30  中年
98   25      3  中年
99   29     26  老年

[100 rows x 3 columns]

In [38]:
# 查看代码中各区间中包含的数据个数
data2.年龄.value_counts()

年龄
少年    26
中年    26
青年    25
老年    23
Name: count, dtype: int64

In [ ]:
# 总结 
# cut 可以自主设置区间值进行数据区间的设置
# qcut不可以自主设置区间值进行数据区间的分类 但可以设置区间的个数